import '@/assets/css/dropdownmenu.css';
import '@/assets/css/sidebar.css';
import '@/assets/css/style.css';
import BootstrapJavascript from "@/components/bootstrapJavascript";
import 'bootstrap-icons/font/bootstrap-icons.css';
import "bootstrap/dist/css/bootstrap.min.css";

import NextTopLoader from "nextjs-toploader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader color="#ff0000"  />
        {children}
        <BootstrapJavascript />
      </body>
    </html>
  );
}
